### PR TITLE
Update README.md with useful first run info

### PR DESCRIPTION
**Pull request by noroot**
Added more useful info into README.md for first-comers to run system out of the repo

### CODE REVIEW

**Comment by hsoft** [comment]
The process is already documented in the `doc` section. Having this section in the README isn't a bad idea, but I think it would be better to reference the doc instead, informing the visitor that emulating from a modern environment is possible and easy.

**Comment by noroot** [comment]
I made this changes inside README.md because of this thread https://habr.com/en/news/t/470832/ , some people read "you have to do glue code by yourself" and stops trying to launch collapseos. This just for newbies who can be encouraged from first glance at README.md if they understand that they can run code successfully. It's a good practice to show how you can run project from start page to attract more people to participate, that's my point.

**Comment by hsoft** [comment]
The problem that happened in the situation you refer to is not because there wasn't handholding in the README, but because there was misunderstanding when reading the doc page: You have to write glue code yourself *when you run the RC2014 emulator*. When you use the builtin emulator, only `make && ./shell/shell` is necessary.

If the doc is unclear and leads to misunderstanding, this is what we should fix.

**Comment by hsoft** [comment]
Closing due to inactivity. If you want to improve the docs as per my latest comment, please submit a new PR.

**Pull request closed without merging**
