### PR TITLE
Check spelling

### PR DESCRIPTION
**Pull request by link2xt**

### CODE REVIEW

**Comment by hsoft** [comment]
I will be rejecting this for the same reason as #3, and I will also be rejecting you two other PRs for similar reasons.

Thanks for those improvement proposals, I appreciate the gesture, but they have no substance, they don't actually solve a problem. Those kind of "drive by PR" do irritate me because I have to spend time managing them and I don't want to encourage them, so I reject them.

Accepting your PRs would be the quicker than writing this long message, and it would actually make the project better (but, as I wrote, not in a substantial manner), but then I'd be losing my moral high ground for refusing further of those PRs, hence this message.

I understand that you're looking at an "entry point" into the project, and I'm glad that you do, but please, do find something substantial to fix. If the learning curve is too steep, I can probably help you (especially if the documentation is insufficient).

**Comment by link2xt** [comment]
I was reading documentation blocks and stumbled upon some typos. Decided to fix them all in a batch and continue reading from there, that's it.

**Comment by hsoft** [comment]
Yes, that's what I mean by "drive by PR".

**Comment by hsoft** [comment]
Now that I see that you're beyond "driving by", I'll accepts those 3 PRs instead. thanks.

**Pull request merged**
