### PR TITLE
Random impl

### PR DESCRIPTION
**Pull request by keithstellyes**
Add random functionality to the kernel, I wanted to write some games to help drive interest and as proofs-of-concept. Ideally kernel feeds entropy into it, so that's why it's located there (and not just a mere user-space library)

Also add a small dice app to demonstrate usage of it

image

### CODE REVIEW

**Comment by Clanmaster21** [comment]
I took a (very) brief look on the blog post referenced, have you checked if it's licensed or copyrighted or anything? I couldn't see it mentioned, so it might be worth checking.

**Comment by keithstellyes** [comment]
I've e-mailed him, looking at the blog-post again, it looks like that was a compiler output, not his actual implementation. Will update the comment to clarify, too.

E-mail:

> Hi John,
> A few years ago, you posted some Z80 assembly code here:
> 
> http://www.retroprogramming.com/2017/07/xorshift-pseudorandom-numbers-in-z80.html
> 
> I'm trying to add random number functionality to CollapseOS, a Z80 OS,  however, it is unclear whether you are releasing this code for others to use.
> 
> CollapseOS GitHub: https://github.com/hsoft/collapseos/
> The Pull Request with that code: https://github.com/hsoft/collapseos/pull/47
> High-level article on the OS from Vice: https://www.vice.com/en_us/article/ywaqbg/collapse-os-is-an-open-source-operating-system-for-the-post-apocalypse
> CollapseOS is licensed under GPL3 (See COPYING on the repo). Can you update the blog-post to clarify whether you release that snippet for others to use/its license?
> 
> Note: I don't officially represent CollapseOS or anything, I'm just a contributor
> 
> Thanks,
> Keith Stellyes

**Comment by Clanmaster21** [comment]
Looks good, I don't think it is compiler output though, I think he's comparing it speedwise to a compiler output, since the given code is 86 cycles and the C one is 1200. I can't imagine how it could turn out as 1200 cycles though, even the slowest method I can think of would be around 400 cycles, by doing 7+8+9=24 individual rotate through carries, to each individual register so 48 lots of 8 cycles.

**Comment by keithstellyes** [comment]
Oops, I think you're right.

Will see what he says

**Comment by Clanmaster21** [comment]
Sounds like a plan

**Comment by keithstellyes** [comment]
John, the original author of this RNG generator has approved, however currently my comment is misleading suggesting this is C compiler output, @hsoft please don't merge until I update that comment.

John's approval:

> Hi Keith,
> 
> Thanks for your email.  Feel free to use the code under any
> appropriate free usage licence.  If possible, please can you
> acknowledge me in a source code comment.
> 
> The same applies to any of my other code.
> 
> I'll update the blog soon to confirm usage.
> 
> Kind regards,
> 
> John

**Comment by Clanmaster21** [comment]
I'm uncertain it will get merged, I'm unsure how vital RNG is to the system. I was reading up on how there's an internal memory refresh counter often used for pseudorandom number, which can be accessed by doing "ld a, R" and "ld R, a" according to official documentation. I haven't checked if zasm supports these though, there still seem to be some unsupported commands, but worst case scenario you could hardcode in the opcode as a .db .

**Comment by keithstellyes** [comment]
Do you happen to have links on that? It seems interesting, but I wonder how well supported it is by emulators, will have to take a peek at the libz80 code

I did find this:

https://retrocomputing.stackexchange.com/questions/2244/how-was-early-randomness-generated

> ...[G]ames on the Z80 CPU used the bottom 7 bits of the R register, which is actually there to provide a refresh signal for DRAMs, and increases by 1 every instruction fetch.

**Comment by Clanmaster21** [comment]
I can't remember where I read about its usage in RNG, but [this](http://www.myquest.nl/z80undocumented/z80-documented-v0.91.pdf) link explains it well. It's in section 6.1 .

**Comment by keithstellyes** [comment]
Just read it, thanks! Seems like a good resource to add to the bookmarks.

It does look like libz80 implements the behavior (`Z80Context.R`, and looking the source code it's definitely getting mutated). I suppose that makes sense that it would, it sounds like something a lot of apps are dependent on. So I'll see if I can go down the `ld a, R; ld R, a` route tonight

**Comment by Clanmaster21** [comment]
Maybe you could use that as your entropy source, and move it to /lib/ instead of the kernel, if you intend for other apps to be able to rely on it.

**Comment by keithstellyes** [comment]
Perhaps. Are you suggesting random be 100% moved out of the kernel, and that just be used as a seed to the RNG?

Or are you thinking an entropy random module thing in the kernel? Because to me it does make sense for entropy to be done at the kernel-level, but I don't think any of us are clamoring to have some complex entropy random-module here.

**Comment by Clanmaster21** [comment]
I meant rather than getting entropy from the kernel, you separate your code entirely from the kernel and use the memory refreshes as an entropy source for seeding. I'm trying not to call any shots since I've only been here like three days, but I feel like trying to get it into the kernel isn't the right approach, if at all. I feel like your suggestion to drive up interest with making games is out of place in this project, but I could see an argument for having an RNG module on hand, for Monte-Carlo simulations and the like (which as far as I'm aware would require something a bit more complex), which is why I think you'd be better off trying to make it an additional module if anything.

**Comment by keithstellyes** [comment]
That's fair, and I can buy that. For Monte-Carlo, that's what middle square method was designed for, right? I'm inclined to think this would work "well-enough" if you're actually in the situation where you're reliant on CollapseOS+Z80 for Monte Carlo simulations, but I wouldn't know. 

From that perspective, yeah outside of kernel entirely and just take seed from the user (who can presumably roll dice or something). I'll wait and see what @hsoft has to say here

**Comment by Clanmaster21** [comment]
Yes, I think so at least. I think the standard is the Mersene twister, but according to some searching an implementation of it is 3KB on its own, so I think something simple like what you gave would be a good compromise.

**Comment by keithstellyes** [comment]
There is: http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/TINYMT/index.html

https://github.com/MersenneTwister-Lab/TinyMT 127 bits for the 32 bit version. But I'm having a hard time finding any info of it actually being used or any data on how good it is v. other solutions. Probably better than what we have here, but that definitely looks more complicated.

Here suggests to multiply xorshift by some constant: https://stats.stackexchange.com/questions/40680/is-xorshift-rng-good-enough-for-monte-carlo-approaches-if-not-what-alternatives

Seems fairly involved to be confident what our best solution is here, but also I don't wanna let perfect be the enemy of good. 

My general thought is this is "good-enough" for the time-being, and to wait until more development has taken place to get a better idea of how random random needs to be.

**Comment by Clanmaster21** [comment]
It'd take a lot of effort to try porting that to the z80, and I doubt we could do so easily and efficiently. I was looking into writing a multiplication function, I think mine was 25 bytes but if I can make it a bit smaller without sacrificing speed I might try getting it added, multiplication can be useful for some interesting optimisation tricks sometimes, but again I'd want to try identifying some cases before I suggest it else it just isn't needed. I don't know much about PRNG in terms of statistical analysis, so I agree that this should be good enough for now.

**Comment by hsoft** [comment]
If the only actual use case for random numbers are games, I'd be tempted to leave this code out. I can't think of an actual use case. Can anyone do?

I'm sorry that you worked on this before I wrote #53, expectations weren't clear.

Otherwise, the code looks fine to me.

**Comment by Clanmaster21** [comment]
As I said before, there's Monte Carlo simulations, but in light of `contributing.md` I don't think it's the job of CollapseOS to provide such tools. There's a few methods [here](http://www.hugi.scene.org/online/coding/hugi%2017%20-%20coaax.htm) (scroll down to "Complex example") and [here](http://lolengine.net/blog/2012/4/3/beyond-de-bruijn) that utilise randomness for the sake of optimisation (the second one not so much, but the idea of processing an input to get a value in a small lookup table can be implemented by shifting and xoring), however the exact method and numbers are always very unique to the case, so I don't think I'd be relying on this code if I were to implement methods similar to either of these.

**Comment by RangerMauve** [comment]
Would this RNG be enough for cryptography? That'd be the main usecase of having a kernel-provided RNG in my opinion. Though I guess having an external hardware module for something like that might be better.

**Comment by Clanmaster21** [comment]
I don't think so, I think to be cryptographically secure you need a real life truly random entropy source, which this lacks. The original idea was to have it in the kernel to gather entropy from the user, which could make it cryptographically secure I think, but again I'm uncertain if cryptography if within the scope of this project.

**Comment by f4grx** [comment]
For cryptography you can use pseudo randoms but they have to be cryptographically secure, that means, you cant go back in the stream given the current state.

To achieve that, hashes are used (mainly sha256), this allow to generate a long stream of pseudorandomness good enough for cryptography, but you have to reseed periodically to avoid getting a predictable sequence.

Schneier did a lot of work with secure PRNGs.

Could be fun to do in z80 assembly, but I'm not sure cryptography is the real job of CollapseOS.

**Comment by f4grx** [comment]
With some precautions, it is possible to get entropy from randomly timed events, or unpredictable values, like the LSB of an ADC connected to ... nothing. It is also easy to build a noise source from a reverse biased transistor, it can be sampled with an ADC or with a simple schmidt trigger. That would be a true random generator. The problem is, the data rate of these TRNGs is slow, that's why we use them to seed pseudorandom generators.

But the practice is that anything based on modulos, multiplications, and linear operations is not "strong" enough for cryptography

(I work in smart cards embedded programming)

**Comment by Clanmaster21** [comment]
I see, that makes sense. From what I recall, the SHA256 algorithm isn't all that painful, I think it'd be easy to do, but hard to do well, since we're dealing with 32 times as many bits as can be processed at once. It certainly would be interesting to try, but I agree that I don't think it's a goal of CollapseOS. I feel like random polling of the sign / parity flag could work too, if you rewrite an interrupt to do it, I'm unsure which would be suitable though, I don't think the z80 has a programmable interrupt timer which would be ideal.

**Comment by f4grx** [comment]
SHA-256 would be massive for a 8-bit cpu.
Maybe some irreversible function can be built from XTEA, which is still strong, not like its friends TEA and XXTEA
https://en.wikipedia.org/wiki/XTEA
https://en.wikipedia.org/wiki/Cryptographic_hash_function#Hash_functions_based_on_block_ciphers

This would also make a block cipher available without writing more code :)

**Comment by keithstellyes** [comment]
Yeah, given the "only microcontrollers", even Monte Carlo seems out of scope. If nobody has any objections, going to close this.

> I'm sorry that you worked on this before I wrote #53, expectations weren't clear.

It's fine, I learned _a lot_ about the system from doing this, so while there's no concrete result, I certainly gained a lot in learning about making a new app, inserting code into kernel, etc. Much of which I feel like will help me become a better contributor here going forward.

WRT being in kernel: I think my initial gut reasoning was for as you see in say the Linux architecture where you have multiple entropy sources writing to one place. However, without things like multi-threading, that seems difficult, plus such a system would have overhead. And for our purposes, I'm sure the `ld a, R` `ld R, a` would be sufficent in conjunction with some random machine.

WRT crypto-random, I never really considered it as a target of this branch ever.

WRT hashing/checksums: I think it makes a lot of sense to have at the very least some sort of checksum library. In terms of bootstrapping the system in a real-world scenario, one of the ways I had pictured in my head was manually programming a memory unit manually with a DIP switch and a button to manually write the binary. This of course would be very error-prone, so some sort of checksum would be good here

**Comment by keithstellyes** [comment]
Closing this PR per discussion here, nobody wants it, and I've been convinced against it. See no reason to keep it alive.

**Pull request closed without merging**
