### PR TITLE
a recipe for the ZX Spectrum

### PR DESCRIPTION
**Pull request by devisn**
Sinclair ZX Spectrum is a challenging Collapse OS target due to:
* absense of standard communication protocols, with the expansion egde connector requiring complex additional hardware;
* cassette tape storage as the only medium supported out-of-the-box;
* 16K ROM space with no paging, 7K memory-mapped screen, and the infamous contended memory, limiting the resources further against the competitors.

This recipe builds a RAM-based kernel capable of self-assembling on the 48K model with tape storage. The ZX Spectrum firmware routines are used extensively for console and tape handling, which requires the `IM 2` interrupt mode of the Z80. Tape is accessed in two ways, via a read-only block device abstraction (required for `zasm`) and a set of short read/write applications directly bridging the MMAP blkdev and file system to tape. The assembly of the kernel binary can be done with the tape-based CFS as the source and the bare MMAP blkdev as the destination. `Zasm`, `ed`, and tape applications are included into the RAM kernel binary. The MMAP size is 16K, the remaining userspace is app 7K.

### CODE REVIEW

**Comment by hsoft** [comment]
Whoa, this is really cool. I don't have the hardware so I have a limited ability to help you out with it. Have you tested it on an emulator with success?

**Comment by devisn** [comment]
> Whoa, this is really cool. I don't have the hardware so I have a limited ability to help you out with it. Have you tested it on an emulator with success?

Thank you very much, I've tested it on Fuse, including self-assembly with the emulated tape. There is a file Boot.tap ready to load into an emulator, and I've converted the sources as well. Tape assembly is really slow, but it works..

**Comment by piranna** [comment]
I love the ZX Spectrum, would be nice of having it running Forth and CollapseOS :-D

**Comment by hsoft** [comment]
Great, I'll give it a try when I have the time. I'm on a self-imposed 2 weeks break from Collapse OS (this project tends to suck me in).

I suppose that you've started this work before the conversion to Forth. Or maybe you just don't like Forth. Either way, if this recipe ends up working, I won't mind converting it to Forth myself.

Meanwhile, if ZX Spectrum owners could confirm that the recipe work on their hardware, it would be great!

**Comment by devisn** [comment]
> I love the ZX Spectrum, would be nice of having it running Forth and CollapseOS :-D
I'm not familiar with Forth :(  This is a z80 port, but there's a lot of Spectrum features involved, so some may be useful for a Forth port too

**Comment by devisn** [comment]
> I love the ZX Spectrum, would be nice of having it running Forth and CollapseOS :-D


> I suppose that you've started this work before the conversion to Forth. Or maybe you just don't like Forth. Either way, if this recipe ends up working, I won't mind converting it to Forth myself.

I've started it in the early May, while it still was the master. I don't know how Forth machine works, but the i/o is quite simple here, so it might be possible to plug these vid/kbd modules in. It's great that Forth has enumerated blocks, so working with tape may be easier (or may be harder, depending on how it treats files). It's of course tape support which has taken so much time

**Comment by hsoft** [comment]
I had a hard time respecting my self-imposed Collapse OS break. I had to give it a try. I successfully loaded Boot.tap in fuse using your instructions and got to the Collapse OS prompt. nice!

I have yet to look at the code in more details, but with regards to the instructions, I have a few remarks.

1. Would it be possible to add a section about emulation? Maybe mention that this works on fuse with the opense ROM. Maybe add some hand-holding instructions in the lines of "load Boot.tap in the tape peripheral then run commands mentioned below".
2. I understand that because of the TAP format, some manual steps are required to end up with proper .tap files, but other recipe have makefiles to facilitate binaries building. Maybe go as far as possible with makefiles and then rely on manual steps?

What do you think?

**Comment by devisn** [comment]
> 1. Would it be possible to add a section about emulation? Maybe mention that this works on fuse with the opense ROM. Maybe add some hand-holding instructions in the lines of "load Boot.tap in the tape peripheral then run commands mentioned below".
Yes, I have to think more about emulation. It seems critical, for example, that the tape traps are omitted for loading (especially assembly) but used for saving (in case of Fuse; there may be other emulators as well, including those without the 'live' tape mode). Have yet to test it with openSE (and other ROMs), as tape drivers depend on the original ROM, not quite the documented entry points.
On the other hand, there may be some unemulated issues, such as the 128K ULA bug, I've put the INT tables so that to avoid that, but this is a test for a real hardware... 

> 2. I understand that because of the TAP format, some manual steps are required to end up with proper .tap files, but other recipe have makefiles to facilitate binaries building. Maybe go as far as possible with makefiles and then rely on manual steps?
It's harder for me to do, one should re/write a set of tools (which is quite legit e.g. for linux) for converting a boot binary to .tap and a cfs image to .tap, following the format description (one has to XOR every byte in the data block to obtain the final CRC byte, attach headers where needed etc). A makefile would end up with os.bin, and then these tools have to do the rest. I've seen a similar set of tools in other recipes, but I can't do them myself at this stage :)

**Comment by hsoft** [comment]
With regards to emulation, I didn't mean that it should support opense. What I meant is that the README should document the requirements for an emulation setup that is known to work.

**Comment by hsoft** [comment]
Thanks, this is great, merging. Because I'm not familiar with the platform yet, I can't fully test it, but it looks good as it is. I know I wrote earlier that I didn't mind converting it to Forth, but now that I look closer, it looks like quite an undertaking and without having a real machine to run it on, I know I'll lack motivation.

One day, maybe I'll get my hands on one.

**Comment by devisn** [comment]
Thank you! Meanwhile I hope to get some courage and study the Forth branch
> One day, maybe I'll get my hands on one.

**Pull request merged**
