### PR TITLE
Optimised intoXX functions

### PR DESCRIPTION
**Pull request by Clanmaster21**
Rewrote intoXX functions to mainly rely on intoHL, as the HL instructions are smaller and faster. Also removed some redundant push and pop instructions. I edited the given unit tests to test these, and they seem to work as expected.

### CODE REVIEW

**Comment by Clanmaster21** [comment]
I forgot to add, from the documentation I found on th z80 this code should be 7 bytes smaller, with 2 bytes and 4 cycles saved in intoIX (not including that saved in the call of intoHL), 1 byte and 14 cycles saved in intoHL, and 4 bytes and 28 cycles saved in intoDE (again not including the cycles saved in the call).

**Comment by hsoft** [comment]
That looks like a nice asm trick I didn't know about. Thanks! will look into it soon.

**Comment by hsoft** [comment]
I give up. At the risk of looking foolish, you'll have to explain this trick to me...

Doesn't `ld (.load+1), hl` results in writing to ROM (core.asm is pretty much always placed in ROM)?

**Comment by hsoft** [comment]
Yeah, as I think more about it, it seems like I understood well what this was about. It's a clever trick, but unfortunately it can't be used because this code has to be able to run from ROM.

**Comment by Clanmaster21** [comment]
Ah, I'd overlooked that, fair enough. I'll keep that in mind and try again then, the optimisations of intoIX and intoDE should still work at least.

**Comment by Clanmaster21** [comment]
No problem, I'm happy I could contribute. I noticed the tabs a little too late, I'll make another commit to correct it, sorry about that.

**Comment by hsoft** [comment]
This is good stuff, thanks. Merging.

**Comment by Clanmaster21** [comment]
Perfect, I look forward to contributing further too.

**Pull request merged**
