### PR TITLE
ed: auto increment ED_CURLINE

### PR DESCRIPTION
**Pull request by nopjmp**
This increases the binary by 1 instruction, but feels useful following at least GNU ed's behavior.

### CODE REVIEW

**Comment by nopjmp** [comment]
nevermind, I just realize the bug I introduce here.... I'm not even sure if this is something ed should have but I feel it would be useful for listing a program quickly to the screen.

**Comment by schierlm** [comment]
probably add ed's `z` command instead...

`z25` is the same as `+1,+25p`

and just `z` will repeat the last `z` command (i.e. it remembers the number of lines you want to see) and so you can quickly page through the file.

As someone who actually used GNU ed, this was the first command I tried in this ed, and it was not available.

Another command that I would consider useful is `n` - even if just the version without arguments that prints the current line number - so you can do some counting to easily find the correct line numbers to add/delete. But the full `n` with arguments (printing the given lines with their number prefixed) would make it even easier as you do not have to count any more :)

**Comment by hsoft** [comment]
ed's implementation is at the the moment very incomplete. The goal is to bring it as close as its UNIX cousin, except for explicit mentions in the README. So anything not like UNIX's ed can be considered a todo.

**Comment by f4grx** [comment]
How does such an editor work? In particular, how is handled insertion and suppression of lines? Is the whole file held into RAM? is it a linked list of line entries?

**Comment by hsoft** [comment]
@f4grx for usage, I refer to you to UNIX's `ed` documentation which is ample. For implementation details, see https://github.com/hsoft/collapseos/blob/master/apps/ed/main.asm#L1

**Pull request closed without merging**
