### PR TITLE
cpHLDE and writeHLinDE improvements

### PR DESCRIPTION
**Pull request by Clanmaster21**
Pretty major improvements to both of these, cpHLDE is now 5 bytes shorter and between 9 and 12 cycles faster due to branching, and writeHLinDE is now 2 bytes shorter and 21 cycles faster.

### CODE REVIEW

**Comment by Clanmaster21** [comment]
I've put these improvements in a different PR since the others edited functionality, whereas provided I haven't messed up these ones don't.

**Comment by keithstellyes** [comment]
Yay, more optimizations :) LGTM at least, and tests definitely passing, (though I'm not the approver OFC)

**Comment by Clanmaster21** [comment]
That's good, I try to test everything myself, but things slip through sometimes, like when I tried using self modifying code.

**Comment by keithstellyes** [comment]
Just trying to affirm it looks good and help out :)

On that note, I was playing with the idea of writing a Brainfuck JIT compiler as it's an easy language to write implementations of, esp. since I wrote a JIT compiler for it in C a while back

**Comment by hsoft** [comment]
Whoa, it's embarrassing how I sometimes write inefficient code... This is of course a major improvement over my older messy code. Merging, thanks!

**Pull request merged**
