### PR TITLE
Out of bounds FSDEV addr request is not an error

### LINKED ISSUE #56: fls in an emulated FS gives errors after a new file is created
Any time I create a new file in the emulated filesystem, `fls` starts giving "Out of bounds" errors. Here's a minimal example, using a filesystem that just has a single empty file:

```
$ rm cfsin/*
$ touch cfsin/empty
$ shell/shell
Initializing filesystem
Collapse OS
> fls
empty
> fnew 1 dest
> fls
empty
dest
Out of bounds FSDEV addr request at 512 / 288
Out of bounds FSDEV addr request at 512 / 288
```

### PR DESCRIPTION
**Pull request by jes**
This message is triggered every time you create a new file inside the
emulator, because fnew does not initialise the whole block, only the metadata.

Fixes #56.

### CODE REVIEW

**Comment by jes** [comment]
It's possible that I'm wrong about this and have just grossly misunderstood what the message is trying to communicate.

**Comment by jes** [comment]
I don't think this is ready to merge yet, because if you try to create a second file, the second file doesn't subsequently show up in fls, so there is definitely more to this that I've not understood.

**Comment by jes** [comment]
So I think that should be it now. "Abolish fsdev_size" is the commit that actually fixes the filesystem.

Error number 1 in response to an FS_ADDR_PORT read no longer exists, but rearranging the error codes would just needlessly break existing compiled systems, so probably better to leave alone.

**Comment by jes** [comment]
@hsoft I've squashed these commits into one now.

This fixes a buffer overrun in reading the filesystem image, and allows you to create more than 1 file in the emulator, by treating the device as a fixed-size block device instead of a magical device that automatically grows when you write past its end.

Before:
```
$ shell/shell
Initializing filesystem
Collapse OS
> fls
readme.txt
user.h
hello.asm
zasm
ed
> fnew 1 foo
> fnew 1 bar
Out of bounds FSDEV addr request at 7424 / 7200
Out of bounds FSDEV addr request at 7424 / 7200
Out of bounds FSDEV addr request at 7424 / 7200
> fls
readme.txt
user.h
hello.asm
zasm
ed
foo
Out of bounds FSDEV addr request at 7424 / 7200
Out of bounds FSDEV addr request at 7424 / 7200
```

Expected: no error messages, files "foo" and "bar" exist.
Actual: error messages about out of bounds FSDEV addr request, and only "foo" exists.

After:
```
$ shell/shell
Initializing filesystem
Collapse OS
> fls
readme.txt
user.h
hello.asm
zasm
ed
> fnew 1 foo
> fnew 1 bar
> fls
readme.txt
user.h
hello.asm
zasm
ed
foo
bar
```

**Comment by jes** [comment]
This can't be merged due to https://github.com/hsoft/collapseos/issues/55#issuecomment-546640580

**Comment by hsoft** [comment]
Fixed by commit referenced above.

**Comment by hsoft** [comment]
As I write in #56, I closed this too fast. I'll adjust the PR and merge.

**Comment by hsoft** [comment]
Committed in 1b8b113536b560039ac02f224ce02315d9fb0fe5

**Pull request closed without merging**
