### PR TITLE
add link to subreddit

### PR DESCRIPTION
**Pull request by octave-syndicate**
I created the subreddit at https://www.reddit.com/r/collapseos to allow for moderated general discussion of the project. Please let me know who you would like to add to the list of moderators.

(edited to correct subreddit URL)

### CODE REVIEW

**Comment by Redlolz** [comment]
I think you mean this one https://www.reddit.com/r/collapseos but why would this project need a subreddit?

**Comment by octave-syndicate** [comment]
> I think you mean this one https://www.reddit.com/r/collapseos but why would this project need a subreddit?

As the project gains traction I foresee the ecosystem that develops around it requiring a nexus for community discussion that goes beyond the technical aspects of the OS implementation. 

For example, hardware and software projects based on the core of collapse os may develop. Personally, I'd love to see the kit up and running on the Z80-MBC2, would love to see collapse os as the core of some sort of more powerful two-way "broadcast OS" that could be downloaded via a simple radio transceiver to bootstrap users onto a HAM network, recorded onto tape, etc...

The technology of collapse os proper is only the kernel (no pun intended!) around which a vibrant ecosystem would need to develop to make the project actually impactful if the worst should come to pass.

**Comment by hsoft** [comment]
I'm not sure that a subreddit is the most appropriate forum. A mailing list would be sufficient and more apt for a project that aims to build resilience (yes, I know, I'm typing this on github...). I'm also not sure that there's a need for this.

That being said, I haven't set up a mailing list yet and although I feel that this place will only end up gathering dust, I can't be sure, so let's give it a try. But if it doesn't become active in a reasonable, I'll remove the link.

**Comment by octave-syndicate** [comment]
I've set up an IRC channel on freenode and I'm connected via a bouncer so I should be able to stay Op. Let me know if you want any others added to the list of operators. 

I agree a mailing list makes perfect sense given the nature of the project so I'll look into getting that set up as I have time. I still think reddit is a nice-to-have as it provides a soft portal to raise awareness, inspire conversation, solicit ideas, etc... from which interesting bits can be sourced for deeper discussion here or in a mailing-list.

I've managed a few online communities in the past so I see my potential contribution to CollapseOS as a facilitator and organizer usually working in the background. 

irc://irc.freenode.net/collapseos

**Comment by schierlm** [comment]
@octave-syndicate please register the channel with ChanServ (and your nick with NickServ, and associate an email address for password recovery). Having a bouncer in the channel does not hurt for visibility, but is not really required on Freenode for maintaining op. If @hsoft  does not object, you may add me (nick=`mihi`) to the ChanServ access list. I'm not often on Freenode, but my account has been active for 16 years now, I do read my offline memos and I don't mind being on the access list for yet another cool project :)

Also, there are sometimes netsplits happening on Freenode, and in case of op collisions when the net merges, the servers default to de-opping everybody. So if you do not have your channel registered, expect to lose op at the next such event (if anyone bothers to join the channel on the other side of the split while the split is happening).

**Comment by octave-syndicate** [comment]
Hi @schierlm - I've registered the channel with ChanServ as you suggest. Thanks! I've also created a listserv (just one general list for now...I suppose we can add announce and others over time as interest develops.) Really appreciate the offer to Op. Hoping @hsoft chimes in at some point re: who he'd like to add to the list but if I don't hear any objection in 24 hours or so I'll add you.

**Comment by octave-syndicate** [comment]
Just FYI, PR including listserv info here : https://github.com/hsoft/collapseos/pull/75

https://lists.sonic.net/mailman/listinfo/collapseos

**Comment by hsoft** [comment]
I think that my registration for vdupras expired, so that nick would be a bad op. +1 for mihi.

Thanks for setting up the mailing list. What is sonit.net. I see that it's an ISP, yes? It's cool that they offer mailing list service, I was reluctant to set this up myself. Do you have much experience with it? Is it reliable?

**Comment by schierlm** [comment]
```
-NickServ- Information on vdupras (account vdupras):
-NickServ- Registered : Jan 23 20:03:03 2013 (6y 42w 1d ago)
-NickServ- Last addr  : ~vdupras@gentoo/developer/vdupras
-NickServ- Last seen  : Jun 13 20:40:20 2019 (21w 6d 1h ago)
-NickServ- Flags      : HideMail
-NickServ- *** End of Info ***
```

Not sure if that is you, but you should be able to confirm based on the group cloak :D

**Comment by hsoft** [comment]
Yes that's be, but I haven't been hanging on IRC much since I retired as a Gentoo developer.

**Comment by octave-syndicate** [comment]
> I think that my registration for vdupras expired, so that nick would be a bad op. +1 for mihi.
> 
> Thanks for setting up the mailing list. What is sonic.net? I see that it's an ISP, yes? It's cool that they offer mailing list service, I was reluctant to set this up myself. Do you have much experience with it? Is it reliable?

Sonic has a very good reputation and still offers shell accounts, mailing lists, etc... They receive high praise from all quarters, for example : https://www.eff.org/mention/sonicnet-gets-highest-marks-data-privacy-report I honestly can't recommend them highly enough to anyone living within their Northern CA service area. 

It's been a good 30 years since I've Op'd a channel on IRC or admin'd a listserv but I'm pretty confident that with help from the likes of mihi and google it'll all come back in due course. :)

Your IRC nick and @schierlm's should both be Op on IRC. If you send me whatever email addresses you'd like to be associated with administering the listserv via PM I'll add you there as well so we've got some distributed resiliency over all-the-things.

**Pull request merged**
