### PR TITLE
_type: exit if input is not available

### PR DESCRIPTION
**Pull request by link2xt**
Currently when

  BUF _type

is executed, if there is a newline immediately after _type, no input is
available. C< returns 0, and it is stored in the buffer.  _type then
proceeds to read until another newline is reached, and the resulting
buffer contents looks like "\x00xyz\x0d" (in C string notation).

This change makes _type exit early in this case and keep the buffer
unchanged.

_type is used by editor words such as I and F, so this bug affects them
as well.

### CODE REVIEW

**Comment by hsoft** [comment]
Thanks for the PR. That is indeed a problem. We've already talked about the issue on IRC and agreed that the real root of the problem was `MOVE`'s handling of zero-sizes, but even if we fix that, there's still a problem in `_type`: In the scenario you describe, `C<` yields `0x00`, which isn't properly handled.

I'm not sure using `C<?` is such a good idea. It feels kludgy to me. I'd be more inclined to change the `0xd =` to `0x20 <`. What do you think?

**Comment by link2xt** [comment]
The problem with `MOVE` is tracked in #125 and this PR does not fix it, it is indeed separate.

> I'm not sure using `C<?` is such a good idea. It feels kludgy to me. I'd be more inclined to change the `0xd =` to `0x20 <`. What do you think?

Makes sense.

Actually, I am not sure if `C<` returning 0 is not a bug. Shouldn't it block instead?

**Comment by link2xt** [comment]
Block 008 clearly says `C<` should block instead of returning 0. So my intention with `C<?` was not to trigger this behavior.

**Comment by link2xt** [comment]
As decided on IRC, closing this in favor of fixing `(rdln)` to read a new line instead of returning 0 from `C<`.

**Pull request closed without merging**
