### PR TITLE
Add logotype

### PR DESCRIPTION
**Pull request by talentlessguy**
I wanted to make some post apolyptic logo so I took font and terminal from Fallout New Vegas :smile: 

I used [Overseer](https://www.dafont.com/overseer.font) font that is personal use only so I may pick another but first I need to hear if this logo is a good idea.

### CODE REVIEW

**Comment by talentlessguy** [comment]
@hsoft what do you think about this logo?

**Comment by hsoft** [comment]
I'm not sure if the project is ready for some branding or if it should have any, but thanks for the gesture, it looks good. Let's keep it around...

**Comment by talentlessguy** [comment]
@hsoft it is not more like a brand but just a logo so it will be more memorizable :)

I would like to hear some critics or ideas about the logo

> Let's keep it around...

means that PR will be open till the right time comes?

**Comment by Redlolz** [comment]
I'd be careful with that, you don't want to be hit with a DMCA from Bethesda.

**Comment by talentlessguy** [comment]
@Redlolz, yeah I'll better change it without having copyrighted stuff in it

**Comment by pinacoelho** [comment]
```
/---\ /---\ |     /---\ +---\ /---- +----  /---\  /----
|     |   | |     |   | |   | |     |      |   |  |
|     |   | |     +---+ +---/ \---\ +--    |   |  \---\
|     |   | |     |   | |         | |      |   |      |
\---/ \---/ \---- |   | |     ----/ +----  \---/* ----/*
 -- The End is Nigh: Compile !!! --
```

**Comment by talentlessguy** [comment]
Guys, I decided to remove graphic part so logo can be displayed in the CollapseOS itself because it is text:

```
   ______      ____                      ____  _____
  / ____/___  / / /___ _____  ________  / __ \/ ___/
 / /   / __ \/ / / __ `/ __ \/ ___/ _ \/ / / /\__ \
/ /___/ /_/ / / / /_/ / /_/ (__  )  __/ /_/ /___/ /
\____/\____/_/_/\__,_/ .___/____/\___/\____//____/
                    /_/
```

**Comment by f4grx** [comment]
Could be RLE encoded to save valuable ROM space :)

**Comment by hsoft** [comment]
Although ascii art is rather cool looking and fun and considering the new contribution guidelines, I'd be inclined to reject this PR on the basis that it doesn't advance the project towards its goal and could mistakenly make someone think it's an ironic project.

**Comment by talentlessguy** [comment]
@hsoftс, imo project identity is also important but yeah you're right. Should I close it?

**Pull request closed without merging**
