### PR TITLE
README.md: typo

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by elimisteve** [comment]
Interesting project! I first saw it when it was announced, and really like your reasoning for switching to Forth.

There's a really fascinating talk I think you should watch called ["The 30 Million Line Problem"](https://www.youtube.com/watch?v=kZRE7HIO3vk). In it, the speaker talks about how the layers and layers of crap have accumulated over the years in software (very true -- something you have also mentioned). He focuses on the many millions of lines making up modern OS kernels, and proposes a really interesting solution that you may want to pursue that would standardize how hardware interacts with the OS, thereby eliminating the need for software drivers at all -- the main cause of kernel bloat over the last 25 years!

**Comment by hsoft** [comment]
Thanks, but see #3 .

As for standards, well, you know about that xkcd.... One thing that also simplifies the code is to assume your user is proficient in electronics tinkering. When that's part of the specs, things get a lot simpler, code-wise.

**Comment by elimisteve** [comment]
> He focuses on the many millions of lines making up modern OS kernels, and proposes a really interesting solution that you may want to pursue that would standardize how hardware interacts with the OS, thereby eliminating the need for software drivers at all ...

> > As for standards, well, you know about that xkcd....

@hsoft The video I mentioned describes _the first_ such standard, not the umpteenth, and one that would make it **feasible for every programmer to build their own operating system** that works with a gigantic number of peripherals.

It's a really good idea worth taking seriously.

**Comment by hsoft** [comment]
The video is too long, I've stopped at 38m. I'm not convinced of either the soundness of the idea or the relevance to Collapse OS.

1. His proposal only addresses a tiny fraction of the stack of complexity he denounces.
2. If you take the time to configure your kernel at compile time, only a small part of those 17m lines are going to end up in your kernel.
3. The hardware on those SoC is much more complex than it was in 1990.
4. If every SoC has its own ISA, isn't your operating system going to be targeting that single ISA (or a handful maybe, at the cost of added complexity)? It would then be incorrect to say that it would work "with a gigantic number of peripherals".
5. That code that is in device drivers is still useful and gotta be somewhere. Sure, we can stuff it in the SoC's new super-BIOS hidden behind the ISA, but will you really have eliminated complexity? You would just hide it.

Maybe I'm missing something, but the video is too long. I'd be more interested in seeing a written proposal.

**Pull request closed without merging**
