### PR TITLE
couple of typos

### PR DESCRIPTION
**Pull request by akkartik**

### CODE REVIEW

**Comment by hsoft** [comment]
Thanks for the gesture, but let's not start this. There's tons of typos in those comments, I know it. Fixing them in a piecemeal fashion would mean needless PR noise. I'll go through the bulk of them at once some day.

**Comment by akkartik** [comment]
Sure.

**Comment by 0verk1ll** [comment]
@hsoft I understand that you want to stay focused on writing code for your project, but I think improving the writing quality is critical.
Many people already do not understand the need for the project. Seeing typos in official documents related to the project could further turn people away. I believe having the highest possible writing quality will lend credibility to the project.
I am willing to provide help in this area if you want it. I have minimal coding skills, but I do have English writing skills, so this is the main way I can contribute.
I am not trying to be rude. If you disagree with me, that is fine. I just wanted to share my viewpoint.

**Comment by hsoft** [comment]
I appreciate the gesture, but the project is unfinished and I don't see it as critical that people aren't turned away until then. When I made the reddit post that turned viral, yes, my goal was to have a little exposure, but I rather hoped that, among the exposed crowd, some of the rare people who would have both the inclination and the skill to work on this with me would show up.

The exposure has been much better than expected, but I had to come to the realisation that I'm likely to have to finish this project entirely alone. I'm fine with this (although, seeing how 2020 so far has been kicking collapse into overdrive, I might lack time).

Could typos in the README turn away one of those rare skilled&inclined people I was seeking? I find it unlikely. When the project is finished, I'll polish it. Or when I feel like it. Sometimes, I do this kind of sweeping changes when my mind is dull.

It's great that you want to contribute, really. Typo correcting isn't part of what this project needs, but the skills needed for working on this project *can* be learned by anybody. There are many resources for that. I encourage you to dive into electronics :)

**Pull request closed without merging**
