### PR TITLE
Add CONTRIBUTING.md

### LINKED ISSUE #25: Contributing.md?
Given the recent attention this project has been getting, perhaps a contributing.md could help establish a common formatting standard for contributors and make more clear what kind of contributions the project needs right now.

### PR DESCRIPTION
**Pull request by hsoft**
Here is a first draft of a possible CONTRIBUTING.md. This starts from my own gut feeling, but I would like to avoid making people who were early contributors feel excluded, so I'd like to ask for your feedback (pinging you). What do you think? Fair?

Ping @lupaz @Clanmaster21 @keithstellyes @jes @yur3i @noroot @vlaube-de @talentlessguy @QuercusFelis 

Anyone is of course welcome to comment.

fixes #25

### CODE REVIEW

**Comment by Clanmaster21** [comment]
I'd say it's fair, although I feel that points two and three conflict a little since the most compact code won't necessary be simple in terms of readable. Are you aiming to strike a balance, or is there one which you'd place as more important?

**Comment by talentlessguy** [comment]
CONTRIBUTING.md looks great but it looks like it says that only code contributions are allowed.

> 1. Collapse OS' only goal is to preserve humanity's ability to program
>    microcontrollers with low-tech tools. We accept only contributions advancing
>    the project towards that goal.

So for example, adding something to readme (like in #16) doesn't satisfy the contribution guides? Correct if I'm wrong.

**Comment by hsoft** [comment]
@Clanmaster21 the priority would be simplicity, then compactness, then efficiency. Of course, we also want to be pragmatic: in tight loops, it's logical to prefer efficiency. If my wording isn't clear, I'll think of rewording it.

@talentlessguy That's not the intention of this text to suggest that only code contributions make the project advance toward its goal. Maybe my wording is unclear.

**Comment by hsoft** [comment]
I've updated the text. I hope that it is now clearer.

**Comment by QuercusFelis** [comment]
Sorry about my late response to this. I think everything here is good, but I do have a few comments. One more section detailing acceptable code formatting would be good for those who are ready to contribute, a link to the roadmap webpage would go nicely here, and ressources should be spelled resources.

Speaking of contributing myself, I do have it on my schedule to start putting a pull request together, but I've been quite tied up this week and the last with other, more time-sensitive programming projects.

**Comment by keithstellyes** [comment]
Yeah I am going back to work here soon in a week (was changing jobs), so my time's going to be a lot tighter.

Overall, I think it looks good, I wonder if it would be good to have a basic summary of what skills are _necessary_.

**Comment by QuercusFelis** [comment]
I believe the section on necessary skills would be covered with a link to the roadmap page, which has more details on specifics as well as a skills section of its own. Hopefully, if someone is serious enough to consider contributing, they would take the time to read that.

**Comment by Clanmaster21** [comment]
I think the updated text is clearer, thanks. I'm mostly just worried of crossing the line between simplicity and compactness with my optimisations.

**Comment by hsoft** [comment]
@Clanmaster21 yes, I'm a bit worried too, but I'm sure we'll find that line :)

**Comment by hsoft** [comment]
I've written that document about ramping up skills, uploaded it on the website and updated `CONTRIBUTING.md` (with a new addition about "hand holding").

I'm under the impression that it's adequate as it is now.

**Comment by Clanmaster21** [comment]
It looks good to me. I was reading the new document and skills and I was about to come and recommend "the art of electronics" since I was recommended it in my electronics module last year, but then I kept reading and saw it. There's a few other books on the reading list if you'd like some more introductory texts to put on that page though.

**Comment by QuercusFelis** [comment]
I'd say it's about as ready as it needs to be for now. Any other changes can be made at a later date.

**Pull request merged**
