### PR TITLE
String functions optimised

### PR DESCRIPTION
**Pull request by Clanmaster21**
A few functions have been tweaked, but the biggest changes are in strlen, strskip and toWS, which take around two third of the cycles they used to (although strskip has more overhead). 10 bytes saved total.
toWS had two bytes added inlining the isWS call, and a jump to unsetZ was inlined too, saving a byte. This saved 29 cycles, with the original function being 90 cycles. I looked at other uses of isWS and it's difficult to inline it effectively in every situation, so I haven't inlined it elsewhere.
rdWS had a byte and two cycles saved by inlining a jump to unsetZ.
strskip is the same size, with the loop cut down from 35 cycles to 21 cycles, but 18 cycles are added outside the loop. I expect one character strings are in the minority, so this should save cycles overall.
strlen had 8 bytes saved, with the loop cut down from 38 cycles to 21 cycles, and 18 cycles removed outside the loop.

### CODE REVIEW

**Comment by Clanmaster21** [comment]
I'm gonna need some help interpreting that error, it seemed to pass all the unit tests when I ran them locally at least.

**Comment by hsoft** [comment]
(why did runtests.sh continue after that first failure?? TODO)

This failure means that your changes broke the `avra` assembler. When re-assembled with your changes baked in, it becomes unable to assemble blink_t45.asm from the tests.

**Comment by hsoft** [comment]
It also means that unit tests don't cover the case. Usually, when I encounter a problem like this, I add a new unit test once I've identified the root cause.

**Comment by Clanmaster21** [comment]
Ah makes sense, thanks. I'll take another look over and see if I can spot which cases aren't being tested for.

**Comment by hsoft** [comment]
Re-assembling zasm and avra after changes is something that is easy to forget, but is nonetheless crucial. That's why we have a CI I guess :)

**Comment by Clanmaster21** [comment]
Ah I think I see the issue (an issue at least), in strskip I was trying to be clever and save pushing and popping af by loading a to b, but b would get decremented by cpir, so it'd change the value then loaded back into a.

**Comment by Clanmaster21** [comment]
The issue was that a register wasn't being preserved, should I add unit checks for that? It seems a bit overkill, since you could add those kinds of unit tests to every function for every register. Maybe there could be a routine that checks what registers are preserved by a function pointed to by (IX) or something, and checks that against a list of what registers that function should preserve?

**Comment by hsoft** [comment]
No need to write tests against registers being preserved. This is just something we have to be vigilant about.

**Comment by hsoft** [comment]
Thanks again, this looks good. I'd like, however, to avoid inlining further. I realize that calls come with a big penalty, but the code still moves a lot and allowing code duplication seems unwise to me at this point in time (if I had to review your parseDecimal PR again, I'd say the same thing. but now that's it's there, let's leave it...).

I would be tempted to add that the kind of optimization you're doing is premature because there is a high likelihood of being lost in macro code refactoring at some later point, but I really don't want to stop you because these are all clever changes and you're doing a good job of not hurting readability.

So as long as you're having fun, I see no problem in integrating those changes, except, as I've stated above, code inlining because I have a bad feeling about it. Could you please remove it?

**Comment by Clanmaster21** [comment]
That's fair enough, I wasn't too happy with it either, since before I inlined in order to remove the function entirely, but this time I couldn't. I'll put the function call back in.

**Comment by Clanmaster21** [comment]
That saves two extra bytes too, which is always good.

**Comment by hsoft** [comment]
Good stuff, thanks, merging.

**Pull request merged**
