### PR TITLE
Replace bin2c.sh with a more portable implementation.

### PR DESCRIPTION
**Pull request by grobe0ba**
`xxd' is not available on all systems, and on others does not support
the `-i' flag. Since bin2c.sh relied on a tool that I can't seem to find
a compatible version of, I have included a simple, portable replacement in C.

Usage remains the same:
bin2c ARRAYNAME < inputfile > outputfile.

This change is also reflected in emul/Makefile.

### CODE REVIEW

**Comment by hsoft** [comment]
Good idea, thanks. Because all programs in `/tools` are small and single-file, I'd rather have them all in the same directory, using the same makefile. Would you mind moving it up one level?

Also, I'm curious: what OS are you running? I thought OpenBSD was a good "portability canary" (`xxd` is provided by the vim pkg), but it seems I was wrong :)

**Comment by grobe0ba** [comment]
That's been moved up a level, and the Makefiles updated.

As for the availability of `xxd' in OpenBSD, it turns out you're correct that it is in the vim packages, which I didn't realize and don't have installed. I've been a user of Emacs for many years, and in the last couple mixing between that and Neovim, which doesn't have `xxd'. On Alpine Linux, the `xxd' in use is the Busybox version, which doesn't have the `-i' flag.

**Comment by hsoft** [comment]
Strange, travis stopped working on this project. Your program doesn't compile on a Linux system, it's missing `stdint.h`. But otherwise, it works fine, thanks. I'll merge and add `stdint.h` myself.

**Comment by grobe0ba** [comment]
Could've sworn I had stdint in there. Clang normally complains about such blatantly missing headers...

**Pull request merged**
